load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "containers",
    srcs = ["containers.proto"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@protobuf//:timestamp_proto",
    ],
)